2018-01-11 12:45:55,414:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-11 12:45:55,445:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-11 12:46:04,250:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-11 12:46:04,258:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-11 12:46:04,436:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-11 12:46:09,311:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-11 12:46:09,319:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-11 12:49:59,929:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-11 12:49:59,938:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-11 12:53:43,272:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-11 12:53:43,281:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-11 12:53:46,285:__main__:INFO:SIMULATION FOR control_file_grw_c COMPLETED!!! 
2018-01-11 15:29:51,636:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-11 15:29:51,643:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-11 15:33:04,547:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-11 15:33:04,555:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 12:51:54,192:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 12:51:54,201:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 12:51:54,213:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 12:51:54,258:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 12:51:54,268:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 12:51:54,278:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 12:51:54,288:__main__:INFO:SIMULATION FOR control_file_grw_c COMPLETED!!! 
2018-01-12 12:53:13,889:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 12:53:13,897:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 12:53:13,937:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 12:53:13,947:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 12:53:13,957:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 12:53:13,967:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 12:53:13,977:__main__:INFO:SIMULATION FOR control_file_grw_c COMPLETED!!! 
2018-01-12 12:55:57,319:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 12:55:57,327:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 12:55:57,340:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 12:55:57,349:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 12:55:57,360:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 12:55:57,369:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 12:55:57,379:__main__:INFO:SIMULATION FOR control_file_grw_c COMPLETED!!! 
2018-01-12 14:22:59,754:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:22:59,762:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:22:59,774:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:22:59,784:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:22:59,794:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:24:45,393:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:24:45,401:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:24:45,413:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:24:45,423:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:24:45,433:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:28:54,225:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:28:54,233:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:28:54,246:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:28:54,256:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:28:54,266:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:29:36,380:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:29:36,388:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:29:36,400:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:29:36,410:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:29:36,420:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:31:40,665:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:31:40,709:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:31:40,759:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:31:40,769:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:31:40,780:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:33:27,830:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:33:27,838:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:33:27,852:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:33:27,861:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:33:27,871:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:35:23,021:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:35:23,028:__main__:INFO:
============ Files selected ============
Control file: control_ben.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:36:13,305:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:36:13,312:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:36:13,326:__main__:INFO:SIMULATION FOR control_file_grw_a COMPLETED!!! 
2018-01-12 14:36:13,336:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:36:13,346:__main__:INFO:SIMULATION FOR control_file_grw_b COMPLETED!!! 
2018-01-12 14:37:33,700:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:37:33,708:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:37:33,722:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:37:33,732:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:37:33,742:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 14:39:53,327:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:39:53,334:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:39:53,348:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:39:53,357:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:39:53,368:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 14:40:08,773:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:40:08,780:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:40:08,818:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:40:08,828:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:40:08,861:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 14:40:58,480:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:40:58,487:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:40:58,525:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:40:58,535:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 14:40:58,568:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 14:42:43,583:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:42:43,590:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:42:43,602:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:43:28,486:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:43:28,494:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:43:28,532:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:45:36,513:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:45:36,520:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:45:36,564:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:46:44,235:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:46:44,243:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:46:44,281:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 14:51:31,775:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 14:51:31,782:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 14:51:31,818:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:17:35,174:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:17:35,219:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:17:35,256:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:21:30,885:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:21:30,893:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:21:30,929:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:24:14,616:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:24:14,624:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:24:14,661:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:24:14,662:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_a/trajectory.pdb'
2018-01-12 15:24:14,662:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_b_tmp.pdb'
2018-01-12 15:24:14,662:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 15:24:14,695:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 15:24:14,695:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_b/trajectory.pdb'
2018-01-12 15:24:14,696:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_c_tmp.pdb'
2018-01-12 15:24:14,696:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 15:24:14,729:__main__:INFO:SIMULATION FOR control_growing_c COMPLETED!!! 
2018-01-12 15:24:14,730:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_c/trajectory.pdb'
2018-01-12 15:24:14,730:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_d_tmp.pdb'
2018-01-12 15:24:14,730:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_d.pdb
2018-01-12 15:24:14,764:__main__:INFO:SIMULATION FOR control_growing_d COMPLETED!!! 
2018-01-12 15:24:14,764:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_d/trajectory.pdb'
2018-01-12 15:24:14,765:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_e_tmp.pdb'
2018-01-12 15:24:14,765:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_e.pdb
2018-01-12 15:24:14,798:__main__:INFO:SIMULATION FOR control_growing_e COMPLETED!!! 
2018-01-12 15:24:14,798:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_e/trajectory.pdb'
2018-01-12 15:24:14,799:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_f_tmp.pdb'
2018-01-12 15:24:14,799:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_f.pdb
2018-01-12 15:24:14,832:__main__:INFO:SIMULATION FOR control_growing_f COMPLETED!!! 
2018-01-12 15:24:14,833:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_f/trajectory.pdb'
2018-01-12 15:24:14,833:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_g_tmp.pdb'
2018-01-12 15:24:14,833:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_g.pdb
2018-01-12 15:24:14,867:__main__:INFO:SIMULATION FOR control_growing_g COMPLETED!!! 
2018-01-12 15:24:14,867:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_g/trajectory.pdb'
2018-01-12 15:24:14,867:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_h_tmp.pdb'
2018-01-12 15:24:14,867:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_h.pdb
2018-01-12 15:24:14,901:__main__:INFO:SIMULATION FOR control_growing_h COMPLETED!!! 
2018-01-12 15:24:14,901:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_h/trajectory.pdb'
2018-01-12 15:24:14,901:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_i_tmp.pdb'
2018-01-12 15:24:14,902:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_i.pdb
2018-01-12 15:24:14,935:__main__:INFO:SIMULATION FOR control_growing_i COMPLETED!!! 
2018-01-12 15:24:14,936:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_i/trajectory.pdb'
2018-01-12 15:24:14,936:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_j_tmp.pdb'
2018-01-12 15:24:14,936:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_j.pdb
2018-01-12 15:24:14,971:__main__:INFO:SIMULATION FOR control_growing_j COMPLETED!!! 
2018-01-12 15:24:14,971:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_j/trajectory.pdb'
2018-01-12 15:24:14,971:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_k_tmp.pdb'
2018-01-12 15:24:14,972:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_k.pdb
2018-01-12 15:24:40,056:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:24:40,063:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:24:40,100:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:24:40,100:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_a/trajectory.pdb'
2018-01-12 15:24:40,101:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_b_tmp.pdb'
2018-01-12 15:24:40,101:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 15:24:40,135:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 15:24:40,135:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_b/trajectory.pdb'
2018-01-12 15:24:40,135:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_c_tmp.pdb'
2018-01-12 15:24:40,135:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 15:24:40,169:__main__:INFO:SIMULATION FOR control_growing_c COMPLETED!!! 
2018-01-12 15:24:40,170:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_c/trajectory.pdb'
2018-01-12 15:24:40,170:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_d_tmp.pdb'
2018-01-12 15:24:40,170:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_d.pdb
2018-01-12 15:24:40,203:__main__:INFO:SIMULATION FOR control_growing_d COMPLETED!!! 
2018-01-12 15:24:40,204:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_d/trajectory.pdb'
2018-01-12 15:24:40,204:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_e_tmp.pdb'
2018-01-12 15:24:40,204:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_e.pdb
2018-01-12 15:24:40,238:__main__:INFO:SIMULATION FOR control_growing_e COMPLETED!!! 
2018-01-12 15:24:40,239:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_e/trajectory.pdb'
2018-01-12 15:24:40,239:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_f_tmp.pdb'
2018-01-12 15:24:40,239:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_f.pdb
2018-01-12 15:24:40,273:__main__:INFO:SIMULATION FOR control_growing_f COMPLETED!!! 
2018-01-12 15:24:40,274:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_f/trajectory.pdb'
2018-01-12 15:24:40,274:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_g_tmp.pdb'
2018-01-12 15:24:40,274:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_g.pdb
2018-01-12 15:24:40,309:__main__:INFO:SIMULATION FOR control_growing_g COMPLETED!!! 
2018-01-12 15:24:40,309:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_g/trajectory.pdb'
2018-01-12 15:24:40,309:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_h_tmp.pdb'
2018-01-12 15:24:40,309:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_h.pdb
2018-01-12 15:24:40,345:__main__:INFO:SIMULATION FOR control_growing_h COMPLETED!!! 
2018-01-12 15:24:40,345:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_h/trajectory.pdb'
2018-01-12 15:24:40,345:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_i_tmp.pdb'
2018-01-12 15:24:40,345:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_i.pdb
2018-01-12 15:24:40,381:__main__:INFO:SIMULATION FOR control_growing_i COMPLETED!!! 
2018-01-12 15:24:40,381:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_i/trajectory.pdb'
2018-01-12 15:24:40,381:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_j_tmp.pdb'
2018-01-12 15:24:40,381:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_j.pdb
2018-01-12 15:24:40,415:__main__:INFO:SIMULATION FOR control_growing_j COMPLETED!!! 
2018-01-12 15:24:40,415:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_j/trajectory.pdb'
2018-01-12 15:24:40,416:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_k_tmp.pdb'
2018-01-12 15:24:40,416:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_k.pdb
2018-01-12 15:37:12,794:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:37:12,835:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:37:12,874:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:37:12,874:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_a/trajectory.pdb'
2018-01-12 15:37:12,875:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_b_tmp.pdb'
2018-01-12 15:37:12,875:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 15:37:12,908:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 15:37:12,909:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_b/trajectory.pdb'
2018-01-12 15:37:12,909:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_c_tmp.pdb'
2018-01-12 15:37:12,909:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 15:37:12,942:__main__:INFO:SIMULATION FOR control_growing_c COMPLETED!!! 
2018-01-12 15:37:12,943:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_c/trajectory.pdb'
2018-01-12 15:37:12,943:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_d_tmp.pdb'
2018-01-12 15:37:12,943:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_d.pdb
2018-01-12 15:37:12,977:__main__:INFO:SIMULATION FOR control_growing_d COMPLETED!!! 
2018-01-12 15:37:12,977:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_d/trajectory.pdb'
2018-01-12 15:37:12,977:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_e_tmp.pdb'
2018-01-12 15:37:12,977:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_e.pdb
2018-01-12 15:37:13,011:__main__:INFO:SIMULATION FOR control_growing_e COMPLETED!!! 
2018-01-12 15:37:13,011:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_e/trajectory.pdb'
2018-01-12 15:37:13,011:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_f_tmp.pdb'
2018-01-12 15:37:13,012:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_f.pdb
2018-01-12 15:37:13,046:__main__:INFO:SIMULATION FOR control_growing_f COMPLETED!!! 
2018-01-12 15:37:13,046:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_f/trajectory.pdb'
2018-01-12 15:37:13,046:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_g_tmp.pdb'
2018-01-12 15:37:13,047:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_g.pdb
2018-01-12 15:37:13,081:__main__:INFO:SIMULATION FOR control_growing_g COMPLETED!!! 
2018-01-12 15:37:13,081:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_g/trajectory.pdb'
2018-01-12 15:37:13,082:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_h_tmp.pdb'
2018-01-12 15:37:13,082:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_h.pdb
2018-01-12 15:37:13,117:__main__:INFO:SIMULATION FOR control_growing_h COMPLETED!!! 
2018-01-12 15:37:13,117:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_h/trajectory.pdb'
2018-01-12 15:37:13,118:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_i_tmp.pdb'
2018-01-12 15:37:13,118:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_i.pdb
2018-01-12 15:37:13,153:__main__:INFO:SIMULATION FOR control_growing_i COMPLETED!!! 
2018-01-12 15:37:13,153:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_i/trajectory.pdb'
2018-01-12 15:37:13,154:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_j_tmp.pdb'
2018-01-12 15:37:13,154:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_j.pdb
2018-01-12 15:37:13,188:__main__:INFO:SIMULATION FOR control_growing_j COMPLETED!!! 
2018-01-12 15:37:13,188:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_j/trajectory.pdb'
2018-01-12 15:37:13,189:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_k_tmp.pdb'
2018-01-12 15:37:13,189:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_k.pdb
2018-01-12 15:37:45,467:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 15:37:45,475:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 15:37:52,078:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 15:37:52,087:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 15:37:52,610:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 15:37:52,610:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_b/trajectory.pdb'
2018-01-12 15:37:52,611:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_c_tmp.pdb'
2018-01-12 15:37:52,611:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 15:37:52,645:__main__:INFO:SIMULATION FOR control_growing_c COMPLETED!!! 
2018-01-12 15:37:52,645:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_c/trajectory.pdb'
2018-01-12 15:37:52,645:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_d_tmp.pdb'
2018-01-12 15:37:52,645:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_d.pdb
2018-01-12 15:37:52,680:__main__:INFO:SIMULATION FOR control_growing_d COMPLETED!!! 
2018-01-12 15:37:52,680:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_d/trajectory.pdb'
2018-01-12 15:37:52,681:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_e_tmp.pdb'
2018-01-12 15:37:52,681:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_e.pdb
2018-01-12 15:37:52,715:__main__:INFO:SIMULATION FOR control_growing_e COMPLETED!!! 
2018-01-12 15:37:52,715:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_e/trajectory.pdb'
2018-01-12 15:37:52,716:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_f_tmp.pdb'
2018-01-12 15:37:52,716:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_f.pdb
2018-01-12 15:37:52,750:__main__:INFO:SIMULATION FOR control_growing_f COMPLETED!!! 
2018-01-12 15:37:52,750:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_f/trajectory.pdb'
2018-01-12 15:37:52,751:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_g_tmp.pdb'
2018-01-12 15:37:52,751:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_g.pdb
2018-01-12 15:37:52,785:__main__:INFO:SIMULATION FOR control_growing_g COMPLETED!!! 
2018-01-12 15:37:52,786:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_g/trajectory.pdb'
2018-01-12 15:37:52,786:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_h_tmp.pdb'
2018-01-12 15:37:52,786:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_h.pdb
2018-01-12 15:37:52,822:__main__:INFO:SIMULATION FOR control_growing_h COMPLETED!!! 
2018-01-12 15:37:52,822:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_h/trajectory.pdb'
2018-01-12 15:37:52,823:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_i_tmp.pdb'
2018-01-12 15:37:52,823:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_i.pdb
2018-01-12 15:37:52,857:__main__:INFO:SIMULATION FOR control_growing_i COMPLETED!!! 
2018-01-12 15:37:52,858:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_i/trajectory.pdb'
2018-01-12 15:37:52,858:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_j_tmp.pdb'
2018-01-12 15:37:52,858:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_j.pdb
2018-01-12 15:37:52,892:__main__:INFO:SIMULATION FOR control_growing_j COMPLETED!!! 
2018-01-12 15:37:52,893:__main__:ERROR:Sorry, something went wrong when selecting a PDB from results. First, check if the criteria 
coincide with the report file column name
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 154, in main
    "{}".format(criteria))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 14, in trajectory_selector
    with open("{}/trajectory.pdb".format(trajectory_path), 'r') as input_file:
IOError: [Errno 2] No such file or directory: 'growing_output_j/trajectory.pdb'
2018-01-12 15:37:52,893:__main__:ERROR:Sorry, something went wrong when changing ligand name of the selected PDB
Traceback (most recent call last):
  File "../../grow_for_pele.py", line 161, in main
    "{}_{}.pdb".format(pdb, string.ascii_lowercase[n + 1]))
  File "/home/carlespl/project/Ligand_growing/Growing/template_selector.py", line 47, in change_ligandname
    with open(input_file) as input_f:
IOError: [Errno 2] No such file or directory: '181l_prepared_met_k_tmp.pdb'
2018-01-12 15:37:52,893:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_k.pdb
2018-01-12 16:18:24,022:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 16:18:24,030:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 16:19:55,078:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 16:19:55,085:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 16:23:49,080:__main__:INFO:SIMULATION FOR control_growing_a COMPLETED!!! 
2018-01-12 16:23:49,089:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_b.pdb
2018-01-12 16:27:30,233:__main__:INFO:SIMULATION FOR control_growing_b COMPLETED!!! 
2018-01-12 16:27:30,242:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_c.pdb
2018-01-12 16:31:19,148:__main__:INFO:SIMULATION FOR control_growing_c COMPLETED!!! 
2018-01-12 16:31:19,157:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_d.pdb
2018-01-12 16:35:14,355:__main__:INFO:SIMULATION FOR control_growing_d COMPLETED!!! 
2018-01-12 16:35:14,364:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_e.pdb
2018-01-12 16:39:12,076:__main__:INFO:SIMULATION FOR control_growing_e COMPLETED!!! 
2018-01-12 16:39:12,085:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_f.pdb
2018-01-12 16:42:52,371:__main__:INFO:SIMULATION FOR control_growing_f COMPLETED!!! 
2018-01-12 16:42:52,380:__main__:INFO:Step of the Trajectory selected in 181l_prepared_met_g.pdb
2018-01-12 16:53:18,189:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 16:53:18,197:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

2018-01-12 16:56:24,471:__main__:INFO:We are going to transform the template _mbez_ into _pyjz_ in _10_ steps! Starting...
2018-01-12 16:56:24,478:__main__:INFO:
============ Files selected ============
Control file: control_template.conf
PDB file: 181l_prepared_met
Results folder name: growing_output

